### ISSUE TITLE
Question: Error handling

### ISSUE THREAD

**Issue by twinone** [botgram/botgram#10]
I've been searching through the docs but I can only find something like "all errors are emitted on the bot object".

How can I catch them?
Maybe it's an idea to write a very small sample of error catching so that the process doesn't crash when a network error occurs.

Thanks!

**Comment by jmendeth** [comment]
Yes, errors are emitted as `error` events on the bot object; you can get them by listening to those events:

~~~ js
bot.on("error", (err) => {
  // TODO
});
~~~

If you don't register any listeners, Node.JS exits when an [`error` event is emitted](https://nodejs.org/api/events.html#events_error_events).

If you want to catch errors when sending a message, you can do so [with the `then()` method](https://github.com/jmendeth/node-botgram/blob/master/docs/reply.md#getting-result-and-handling-errors) (in which case the event is not emitted at all).

PS: Network errors when retrieving updates are emitted as `updateError` instead since they're retried.
