### ISSUE TITLE
New commands  won't work if there are more than 5 commands

### ISSUE THREAD

**Issue by MilkyPL** [botgram/botgram#16]
As above. In my [https://github.com/MilkyPL/skelet2bot](https://github.com/MilkyPL/skelet2bot) only first 5 commands work, while later ones are "ignored". There is no error message or anything, they just don't work.

**Comment by MilkyPL** [comment]
UPDATE: after switching command order (command5<=>command6) the command6 will work, but command5 will not.

_Sent from my Htc HTC Desire 820 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MilkyPL** [comment]
UPDATE: this is issue with node-cron. Any command after this won't work:
`bot.all(function (msg, reply, next) {
    cron.schedule("37 21 * * *", function() {
        reply.text("testing cron");
    });
});`

**Comment by jmendeth** [comment]
It seems your code is using the [Telegraf](https://github.com/telegraf/telegraf) library rather than this one?
If that's the case, you should probably [report the issue there](https://github.com/telegraf/telegraf/issues/new). :)

I took a quick look at your code and it seems okay but I'm not very familiar with Telegraf so maybe there's something I'm missing. Also I understand the confusion, both Botgram and Telegraf have turnt out with similar APIs. 😹 

By the way, your bot looks interesting!

**Comment by jmendeth** [comment]
(cleanup)
