### ISSUE TITLE
inline mode

### ISSUE THREAD

**Issue by itsmrTech** [botgram/botgram#17]
https://github.com/botgram/botgram/blob/master/docs/inline.md
it's not documented... so I don't know how to get inline queries...

**Comment by jmendeth** [comment]
Hello! Support for inline mode has been a tough spot since a long time ago, there's #2 tracking it. You can receive inline queries but you still can't answer them.

I'm currently busy on that, plus API 3.3 and API 3.0 (payments). I can't promise anything for the time being but complete support (including docs for inline mode) will probably be available soon.

**Comment by mildsunrise** [comment]
Support for inline queries is implemented in the upcoming v3, so closing this.

**Comment by movstox** [comment]
@jmendeth is there an example of using this new 'inline' mode? thank you
