### ISSUE TITLE
MYSQL QUERY

### ISSUE THREAD

**Issue by jorengo** [botgram/botgram#19]
First of all I would like to thank you for the beautiful work of the scripts. I need to do an implementation for query in a mysql database (pdo) and show the results by the telegram. Can someone help me ?

Best Regards !

**Comment by jmendeth** [comment]
Sorry, closing this since Issues isn't appropriate for asking programming questions. Sites like [StackOverflow](https://stackoverflow.com) are better :)

For you question, you should pick a mysql module such as [this one](https://github.com/mysqljs/mysql#introduction) and when you're able to connect to the DB and issue the query, you can get familiar with Botgram and put both together.
